# Generated by Django 4.0 on 2022-04-14 09:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('deadline', models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
            ],
        ),
    ]
