# Generated by Django 4.0 on 2022-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.CharField(max_length=3),
        ),
    ]
