# Generated by Django 4.0 on 2022-04-14 14:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_taskitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='deadline',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today, message='The deadline date can not be in past')]),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
